---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-http-healthcheck-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
      httpGet:
        path: /_status/healthhz
        port: 80
      initialDelaySeconds: 30
      timeoutSeconds: 1
    ports:
    - containerPort: 80
kind: Pod
metadata:
  name: pod-with-tcp-healthcheck-redis
spec:
  containers:
  - name: redis
    image: redis
    livenessPorbe:
      tcpSocket:
        port: 6379
      initialDelaySeconds: 30
      timeoutSeconds: 1
    ports:
    - containerPort: 6379
