---
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-3
  namespace: qos-example
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    #this is the key spot to call out QOS
    resources:
#      limits:
#        memory: "200Mi"
#        cpu:  "1"
#      requests:
#        memory: "100Mi"
#        cpu: ".5"
#
